import { notFound } from "next/navigation";
import Link from "next/link";
import tables from "../../../generated/tables.json";
import routes from "../../../generated/routes.json";
type Params = Promise<{ table: string }>;
export function generateStaticParams() { return tables.tables.map(table => ({ table: table.name })); }
export default async function Page({ params }: { params: Params }) {
  const { table: name } = await params;
  const table = tables.tables.find(item => item.name === name);
  if (!table) notFound();
  const enumMap = tables.enums as Record<string, string[]>;
  return <main className="shell"><p><Link href="/data-model">← Data Model</Link></p><h1>{table.name}</h1><p className="muted">{table.purpose} <span>Source: <code>{table.sourceFile ?? "schema barrel"}</code>; purpose wording from architecture §5 or schema context.</span></p><h2>Columns</h2><table><thead><tr><th>Name</th><th>Type</th><th>Nullable</th><th>Default</th><th>PK</th></tr></thead><tbody>{table.columns.map(column => <tr key={column.name}><td><code>{column.name}</code></td><td><code>{column.type}</code>{enumMap[column.type] && <div>Values: {enumMap[column.type].join(", ")}</div>}</td><td>{column.nullable ? "yes" : "no"}</td><td><code>{column.default === null ? "—" : String(column.default)}</code></td><td>{column.primaryKey ? "yes" : ""}</td></tr>)}</tbody></table><h2>Keys and indexes</h2><table><thead><tr><th>Name</th><th>Columns</th><th>Unique</th><th>WHERE</th><th>Read/write pattern</th></tr></thead><tbody>{table.indexes.map(index => <tr key={index.name}><td><code>{index.name}</code></td><td>{index.columns.join(", ")}</td><td>{index.unique ? "yes" : "no"}</td><td><code>{index.where ?? "—"}</code></td><td>{index.purpose}</td></tr>)}</tbody></table><p>Primary keys: {table.primaryKeys.length ? table.primaryKeys.map(columns => columns.join(" + ")).join("; ") : "none declared"}. Unique constraints: {table.uniqueConstraints.length ? table.uniqueConstraints.map(item => `${item.name} (${item.columns.join(", ")})`).join("; ") : "none declared"}.</p><h2>Foreign keys</h2>{table.foreignKeys.length ? <table><thead><tr><th>Columns</th><th>Target</th><th>ON DELETE</th><th>ON UPDATE</th></tr></thead><tbody>{table.foreignKeys.map((fk, i) => <tr key={i}><td>{fk.columns.join(", ")}</td><td><Link href={`/data-model/${fk.targetTable}`}>{fk.targetTable}</Link> ({fk.targetColumns.join(", ")})</td><td>{fk.onDelete}</td><td>{fk.onUpdate}</td></tr>)}</tbody></table> : <p>None.</p>}<h2>Checks</h2>{table.checks.length ? <ul>{table.checks.map(check => <li key={check.name}><code>{check.name}</code>: <code>{check.expression}</code></li>)}</ul> : <p>None in latest snapshot.</p>}<h2>Related API endpoints</h2>{table.relatedEndpoints.length ? <ul>{table.relatedEndpoints.map(endpoint => { const route = routes.routes.find(item => `${item.method} ${item.path}` === endpoint); return <li key={endpoint}><Link href={`/api-reference#tag/${route?.module ?? ""}/${route?.method ?? ""}${route?.path ?? ""}`}>{endpoint}</Link></li>; })}</ul> : <p>No direct route handler table reference found. Indirect access through services may exist.</p>}</main>;
}
